addresses:
  label: acorn.location::lang.models.address.label_plural
  view:
    list: $/acorn/location/models/address/columns.yaml
    toolbarButtons: create|delete|link|unlink
    recordsPerPage: 10
  manage:
    form: $/acorn/location/models/address/fields.yaml
    recordsPerPage: 10
