# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: acornassociated.user::lang.user.label

# Model Form Field configuration
form: $/acornassociated/user/models/user/fields.yaml

# Model Class name
modelClass: AcornAssociated\User\Models\User

# Default redirect location
defaultRedirect: acornassociated/user/users

# Create page
create:
    redirect: acornassociated/user/users/preview/:id
    redirectClose: acornassociated/user/users

# Update page
update:
    redirect: acornassociated/user/users/update/:id
    redirectClose: acornassociated/user/users/preview/:id
