# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: 'acorn.user::lang.models.language.label'

# Model Form Field configuration
form: $/acorn/user/models/language/fields.yaml

# Model Class name
modelClass: Acorn\User\Models\Language

# Default redirect location
defaultRedirect: acorn/user/languages

# Create page
create:
    title: backend::lang.form.create_title
    redirect: acorn/user/languages/update/:id
    redirectClose: acorn/user/languages

# Update page
update:
    title: backend::lang.form.update_title
    redirect: acorn/user/languages
    redirectClose: acorn/user/languages

# Preview page
preview:
    title: backend::lang.form.preview_title
