# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: 'acornassociated.user::lang.models.language.label'

# Model Form Field configuration
form: $/acornassociated/user/models/language/fields.yaml

# Model Class name
modelClass: AcornAssociated\User\Models\Language

# Default redirect location
defaultRedirect: acornassociated/user/languages

# Create page
create:
    title: backend::lang.form.create_title
    redirect: acornassociated/user/languages/update/:id
    redirectClose: acornassociated/user/languages

# Update page
update:
    title: backend::lang.form.update_title
    redirect: acornassociated/user/languages
    redirectClose: acornassociated/user/languages

# Preview page
preview:
    title: backend::lang.form.preview_title
