# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: 'acornassociated.user::lang.models.usergrouptype.label'

# Model Form Field configuration
form: $/acornassociated/user/models/usergrouptype/fields.yaml

# Model Class name
modelClass: AcornAssociated\User\Models\UserGroupType

# Default redirect location
defaultRedirect: acornassociated/user/usergrouptypes

# Create page
create:
    title: backend::lang.form.create_title
    redirect: acornassociated/user/usergrouptypes/update/:id
    redirectClose: acornassociated/user/usergrouptypes

# Update page
update:
    title: backend::lang.form.update_title
    redirect: acornassociated/user/usergrouptypes
    redirectClose: acornassociated/user/usergrouptypes

# Preview page
preview:
    title: backend::lang.form.preview_title
