# ===================================
# Filter Scope Definitions
# ===================================

scopes:
    type:
        # Filter name
        label: acornassociated.user::lang.models.usergrouptype.label_short
        # Model Class name
        modelClass: AcornAssociated\User\Models\UserGroupType
        # Model attribute to display for the name
        nameFrom: name
        conditions: type_id in(:filtered)
