# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: acornassociated.user::lang.group.label

# Model Form Field configuration
form: $/acornassociated/user/models/usergroup/fields.yaml

# Model Class name
modelClass: AcornAssociated\User\Models\UserGroup

# Default redirect location
defaultRedirect: acornassociated/user/usergroups

# Create page
create:
    title: acornassociated.user::lang.groups.create_title
    redirect: acornassociated/user/usergroups/update/:id
    redirectClose: acornassociated/user/usergroups

# Update page
update:
    title: acornassociated.user::lang.groups.update_title
    redirect: acornassociated/user/usergroups
    redirectClose: acornassociated/user/usergroups

# Preview page
preview:
    title: acornassociated.user::lang.groups.update_title
